In [1]:
import sys, os

from torchvision.models import vit_b_16
import torch.nn as nn
import torch

from PIL import Image
import torchvision.transforms as transforms
import os

import numpy as np

from matplotlib import pyplot as plt
import cv2


In [2]:
external_repo_path = os.path.abspath('../../deep_feature_reweighting/')
if external_repo_path not in sys.path:
    sys.path.append(external_repo_path)

In [4]:
model = vit_b_16()
model.heads.head = nn.Linear(768,2)
model.load_state_dict(torch.load("F:/model_stuff/vit_isic_final_checkpoint_test.pt", map_location=torch.device('cpu'), weights_only=False))

model2 = vit_b_16()
model2.heads.head = nn.Linear(768,2)
model2.load_state_dict(torch.load("F:/model_stuff/dfr_isic_model.pth", map_location=torch.device('cpu'), weights_only=False))

<All keys matched successfully>

In [6]:
model.eval()
model2.eval()

VisionTransformer(
  (conv_proj): Conv2d(3, 768, kernel_size=(16, 16), stride=(16, 16))
  (encoder): Encoder(
    (dropout): Dropout(p=0.0, inplace=False)
    (layers): Sequential(
      (encoder_layer_0): EncoderBlock(
        (ln_1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
        (self_attention): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=768, out_features=768, bias=True)
        )
        (dropout): Dropout(p=0.0, inplace=False)
        (ln_2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
        (mlp): MLPBlock(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU(approximate='none')
          (2): Dropout(p=0.0, inplace=False)
          (3): Linear(in_features=3072, out_features=768, bias=True)
          (4): Dropout(p=0.0, inplace=False)
        )
      )
      (encoder_layer_1): EncoderBlock(
        (ln_1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
        (self_a

In [5]:
preprocess = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

def tensorize(img_path):
    image = Image.open(img_path).convert('RGB')
    return preprocess(image)

In [9]:
print('GT: 1')
img_name = 'ISIC_0000482'
img_no_patch = tensorize('C:/Users/elmop/Downloads/isic/isic_224/isic_224/raw_224/'+img_name+'.jpg')
img_w_patch = tensorize('C:/Users/elmop/Downloads/isic/manually-insert/manually-insert/'+img_name+'_2.jpg')
print('no patch, model1:')
print(model(img_no_patch.unsqueeze(0)))
print('no patch, model2:')
print(model2(img_no_patch.unsqueeze(0)))
print('patch, model1:')
print(model(img_w_patch.unsqueeze(0)))
print('patch, model2:')
print(model2(img_w_patch.unsqueeze(0)))


no patch, model1:
tensor([[ 3.7089, -3.6933]], grad_fn=<AddmmBackward0>)
no patch, model2:
tensor([[-1.3511,  1.3667]], grad_fn=<AddmmBackward0>)
patch, model1:
tensor([[ 3.1389, -3.1488]], grad_fn=<AddmmBackward0>)
patch, model2:
tensor([[-2.8365,  2.8266]], grad_fn=<AddmmBackward0>)


In [10]:
img_name = 'ISIC_0055136'
img_no_patch = tensorize('C:/Users/elmop/Downloads/isic/isic_224/isic_224/raw_224/'+img_name+'.jpg')
img_w_patch = tensorize('C:/Users/elmop/Downloads/isic/manually-insert/manually-insert/'+img_name+'_2.jpg')
print('no patch, model1:')
print(model(img_no_patch.unsqueeze(0)))
print('no patch, model2:')
print(model2(img_no_patch.unsqueeze(0)))
print('patch, model1:')
print(model(img_w_patch.unsqueeze(0)))
print('patch, model2:')
print(model2(img_w_patch.unsqueeze(0)))

no patch, model1:
tensor([[-1.5936,  1.4076]], grad_fn=<AddmmBackward0>)
no patch, model2:
tensor([[-3.3724,  3.1864]], grad_fn=<AddmmBackward0>)
patch, model1:
tensor([[ 5.6298, -5.7584]], grad_fn=<AddmmBackward0>)
patch, model2:
tensor([[-3.3068,  3.1781]], grad_fn=<AddmmBackward0>)


In [11]:
img_name = 'ISIC_0026774'
img_no_patch = tensorize('C:/Users/elmop/Downloads/isic/isic_224/isic_224/raw_224/'+img_name+'.jpg')
img_w_patch = tensorize('C:/Users/elmop/Downloads/isic/manually-insert/manually-insert/'+img_name+'_2.jpg')
print('no patch, model1:')
print(model(img_no_patch.unsqueeze(0)))
print('no patch, model2:')
print(model2(img_no_patch.unsqueeze(0)))
print('patch, model1:')
print(model(img_w_patch.unsqueeze(0)))
print('patch, model2:')
print(model2(img_w_patch.unsqueeze(0)))

no patch, model1:
tensor([[ 5.6855, -5.6625]], grad_fn=<AddmmBackward0>)
no patch, model2:
tensor([[ 0.5903, -0.5673]], grad_fn=<AddmmBackward0>)
patch, model1:
tensor([[ 5.0750, -5.0889]], grad_fn=<AddmmBackward0>)
patch, model2:
tensor([[-2.6040,  2.5901]], grad_fn=<AddmmBackward0>)


In [12]:
img_name = 'ISIC_0010397'
img_no_patch = tensorize('C:/Users/elmop/Downloads/isic/isic_224/isic_224/raw_224/'+img_name+'.jpg')
img_w_patch = tensorize('C:/Users/elmop/Downloads/isic/manually-insert/manually-insert/'+img_name+'_2.jpg')
print('no patch, model1:')
print(model(img_no_patch.unsqueeze(0)))
print('no patch, model2:')
print(model2(img_no_patch.unsqueeze(0)))
print('patch, model1:')
print(model(img_w_patch.unsqueeze(0)))
print('patch, model2:')
print(model2(img_w_patch.unsqueeze(0)))

no patch, model1:
tensor([[ 5.4245, -5.4052]], grad_fn=<AddmmBackward0>)
no patch, model2:
tensor([[ 0.2641, -0.2448]], grad_fn=<AddmmBackward0>)
patch, model1:
tensor([[ 3.9211, -3.9719]], grad_fn=<AddmmBackward0>)
patch, model2:
tensor([[-2.3874,  2.3367]], grad_fn=<AddmmBackward0>)


In [13]:
img_name = 'ISIC_0014221'
img_no_patch = tensorize('C:/Users/elmop/Downloads/isic/isic_224/isic_224/raw_224/'+img_name+'.jpg')
img_w_patch = tensorize('C:/Users/elmop/Downloads/isic/manually-insert/manually-insert/'+img_name+'_2.jpg')
print('no patch, model1:')
print(model(img_no_patch.unsqueeze(0)))
print('no patch, model2:')
print(model2(img_no_patch.unsqueeze(0)))
print('patch, model1:')
print(model(img_w_patch.unsqueeze(0)))
print('patch, model2:')
print(model2(img_w_patch.unsqueeze(0)))

no patch, model1:
tensor([[ 3.8101, -3.7862]], grad_fn=<AddmmBackward0>)
no patch, model2:
tensor([[-0.9485,  0.9724]], grad_fn=<AddmmBackward0>)
patch, model1:
tensor([[ 3.9183, -3.8688]], grad_fn=<AddmmBackward0>)
patch, model2:
tensor([[-2.3199,  2.3694]], grad_fn=<AddmmBackward0>)
